#!/bin/bash

curl --silent http://10.202.255.252/relay/0?turn=off |jq .ison

#Permet d'éteindre la prise
#option --silent permet que curl ne dise pas ses infos de téléchargement...
#jq sert ici à récupérer la valeur de l'état de la prise 
