#!/bin/bash


#Prise .252
mosquitto_pub -h 10.202.0.65 -t shellies/shellyplug-s-6A64DB/relay/0/command -m "off"


#Prise .253
mosquitto_pub -h 10.202.0.107 -t shellies/shellyplug-s-6A6534/relay/0/command -m "off"


